In [14]:
import pandas as pd
visit =pd.read_csv('air_visit_data.csv')
visit.head()

           air_store_id  visit_date  visitors
0  air_ba937bf13d40fb24  2016-01-13        25
1  air_ba937bf13d40fb24  2016-01-14        32
2  air_ba937bf13d40fb24  2016-01-15        29
3  air_ba937bf13d40fb24  2016-01-16        22
4  air_ba937bf13d40fb24  2016-01-18         6

In [15]:
visit.shape

(252108, 3)

In [19]:
print("visit:")
print(visit.isnull().sum())

visit:
air_store_id    0
visit_date      0
visitors        0
dtype: int64

In [20]:
visit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252108 entries, 0 to 252107
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   air_store_id  252108 non-null  object
 1   visit_date    252108 non-null  object
 2   visitors      252108 non-null  int64
dtypes: int64(1), object(2)
memory usage: 5.8+ MB

In [23]:
import pandas as pd
reserve =pd.read_csv('air_reserve.csv')
reserve.head()

,air_store_id,visit_datetime,reserve_datetime,reserve_visitors
0,air_877f79706adbfb06,2016-01-01 19:00:00,2016-01-01 16:00:00,1
1,air_db4b38ebe7a7ceff,2016-01-01 19:00:00,2016-01-01 19:00:00,3
2,air_db4b38ebe7a7ceff,2016-01-01 19:00:00,2016-01-01 19:00:00,6
3,air_877f79706adbfb06,2016-01-01 20:00:00,2016-01-01 16:00:00,2
4,air_db80363d35f10926,2016-01-01 20:00:00,2016-01-01 01:00:00,5

In [24]:
reserve.shape

(92378, 4)

In [25]:
print("reserve:")
print(reserve.isnull().sum())

reserve:
air_store_id        0
visit_datetime      0
reserve_datetime    0
reserve_visitors    0
dtype: int64

In [26]:
reserve.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92378 entries, 0 to 92377
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   air_store_id      92378 non-null  object
 1   visit_datetime    92378 non-null  object
 2   reserve_datetime  92378 non-null  object
 3   reserve_visitors  92378 non-null  int64
dtypes: int64(1), object(3)
memory usage: 2.8+ MB

In [32]:
import pandas as pd
store =pd.read_csv('air_store_info.csv')
store.head()

,air_store_id,air_genre_name,air_area_name,latitude,longitude
0,air_0f0cdeee6c9bf3d7,Italian/French,Hyōgo-ken Kōbe-shi Kumoidōri,34.695124,135.197853
1,air_7cc17a324ae5c7dc,Italian/French,Hyōgo-ken Kōbe-shi Kumoidōri,34.695124,135.197853
2,air_fee8dcf4d619598e,Italian/French,Hyōgo-ken Kōbe-shi Kumoidōri,34.695124,135.197853
3,air_a17f0778617c76e2,Italian/French,Hyōgo-ken Kōbe-shi Kumoidōri,34.695124,135.197853
4,air_83db5aff8f50478e,Italian/French,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599

In [37]:
store.shape

(829, 5)

In [29]:
print("store:")
print(store.isnull().sum())

store:
air_store_id      0
air_genre_name    0
air_area_name     0
latitude          0
longitude         0
dtype: int64

In [30]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 829 entries, 0 to 828
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   air_store_id    829 non-null    object
 1   air_genre_name  829 non-null    object
 2   air_area_name   829 non-null    object
 3   latitude        829 non-null    float64
 4   longitude       829 non-null    float64
dtypes: float64(2), object(3)
memory usage: 32.5+ KB

In [36]:
import pandas as pd
calendar =pd.read_csv('date_info.csv')
calendar.head()

  calendar_date day_of_week  holiday_flg
0    2016-01-01      Friday            1
1    2016-01-02    Saturday            1
2    2016-01-03      Sunday            1
3    2016-01-04      Monday            0
4    2016-01-05     Tuesday            0

In [38]:
calendar.shape

(517, 3)

In [39]:
print("calendar:")
print(calendar.isnull().sum())

calendar:
calendar_date    0
day_of_week      0
holiday_flg      0
dtype: int64

In [42]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   calendar_date  517 non-null    object
 1   day_of_week    517 non-null    object
 2   holiday_flg    517 non-null    int64
dtypes: int64(1), object(2)
memory usage: 12.2+ KB

In [44]:
print("visit:",visit.duplicated().sum())
print("store:",store.duplicated().sum())
print("reserve:",reserve.duplicated().sum())
print("calendar:",calendar.duplicated().sum())

visit: 2770
store: 0
reserve: 2770
calendar: 0

In [45]:
print(visit.shape)
print(visit.columns)

(92378, 4)
Index(['air_store_id', 'visit_datetime', 'reserve_datetime',
       'reserve_visitors'],
      dtype='object')

In [51]:
visit =pd.read_csv('air_visit_data.csv')
reserve =pd.read_csv('air_reserve.csv')
print("visit shape:", visit.shape)
print("reserve shape:", reserve.shape)
print("visit duplicated:",visit.duplicated().sum())
print("reserve duplicated:",reserve.duplicated().sum())

visit shape: (252108, 3)
reserve shape: (92378, 4)
visit duplicated: 0
reserve duplicated: 2770

In [53]:
reserve[reserve.duplicated(keep=False)].head(10)

,air_store_id,visit_datetime,reserve_datetime,reserve_visitors
47,air_789466e488705c93,2016-01-04 17:00:00,2016-01-04 17:00:00,2
48,air_789466e488705c93,2016-01-04 17:00:00,2016-01-04 17:00:00,2
91,air_e55abd740f93ecc4,2016-01-05 20:00:00,2016-01-05 18:00:00,2
92,air_e55abd740f93ecc4,2016-01-05 20:00:00,2016-01-05 18:00:00,2
121,air_632ba66e1f75aa28,2016-01-06 19:00:00,2016-01-06 15:00:00,2
122,air_632ba66e1f75aa28,2016-01-06 19:00:00,2016-01-06 15:00:00,2
162,air_de692863bb2dd758,2016-01-07 18:00:00,2016-01-07 18:00:00,2
163,air_de692863bb2dd758,2016-01-07 18:00:00,2016-01-07 18:00:00,2
194,air_03963426c9312048,2016-01-08 17:00:00,2016-01-06 15:00:00,4
196,air_03963426c9312048,2016-01-08 17:00:00,2016-01-06 15:00:00,4

In [59]:
print("Negative visitors:",(visit["visitors"] < 0).sum())
print("Negative reservations:",(reserve["reserve_visitors"] <0).sum())

Negative visitors: 0
Negative reservations: 0

In [63]:
print("Duplicate restaurant date:", visit.duplicated(["air_store_id","visit_date"]).sum())

Duplicate restaurant date: 0